ddpg:
  lr_critic: 0.001
  lr_actor: 0.001
  replay_memory_initial_size: -1
  replay_memory_max_size: 10000
  discount_factor: 0.99
  target_soft_update_weight: 0.001
  batch_size: 64
  n_episodes: 1000
  max_episode_steps: 500
  model: 'actor_critic_1'
  plot_file_name: 'AirSim.png'